language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - pip install .
  - pip install coveralls
script:
  - coverage run --source=gitversion setup.py test
after_success:
  - coveralls
